Update Simplified Chinese translation
gyunaev/birdtray pull request #542
Opened 2023-03-04 10:04 UTC by UM-Li

2023-03-04 12:08 UTC, Abestanis requested changes
Hey, thank you very much for these translations! ❤️ 

As a thanks, you can add your name to the [list of translators file](https://github.com/UM-Li/birdtray/blob/master/src/res/translators.md) if you want. That list will show up in the `About` dialog in Birdtray. You can find more information about it in [the `Translators file` section of our wiki](https://github.com/gyunaev/birdtray/wiki/Add-a-new-translation#translators-file).

I have requested some small changes, if you are ok with them please apply them to this pull request. It's not a problem if you don't have the time or are unsure how to do it, I will wait until next weekend and apply them for you if you couldn't do it by then.

@mattuylee if you have the time, could you please also approve the new translations?

2023-03-04 16:39 UTC, mattuylee approved these changes
Thanks for your tweaks and updates! Translations look better now~

2023-03-04 16:39 UTC, mattuylee commented on src/translations/main_zh_cn.ts
> +        <translation>检测到改变时，等待</translation>
personally, "变更" is better. but it's up to you~
```suggestion
        <translation>检测到变更时，等待</translation>
```

2023-03-04 17:09 UTC, UM-Li commented
Hi @Abestanis, I've changed the parentheses and added the comments.  Please let me know if you've found further errors of this type.

2023-03-04 17:11 UTC, UM-Li commented
Hi @mattuylee, thanks for proofreading 😀

#### 垃圾邮件

These folders are on Outlook and my own IMAP server (Dovecot-based with default settings on folder names) respectively.  The shorter version "垃圾" appears to be Thunderbird's naming convention for the default Junk folder, so I made this change.  But there could be service providers who name Junk folders in their own way I suppose.

![folders](https://user-images.githubusercontent.com/6215580/222919378-21f5c9aa-7fd7-455a-b974-31db2e8a3773.png)

#### 检测到改变时

I agree with this one; have changed "改变" to "变更".

2023-03-04 18:16 UTC, Abestanis approved these changes
Thanks a lot, looks good from my side.

@mattuylee Thanks for looking at this so quickly! I'll let you decide if we should keep 垃圾 over 垃圾邮件. Once you have decided this is ready to be merged.

2023-03-14 20:32 UTC, Abestanis commented
I'm going to go ahead and merge this, thank you very much @UM-Li!

@mattuylee If you want to change the translation for `Junk` back, feel free to open another pull request.

2023-03-14 20:32 UTC, merged