czech translation
gyunaev/birdtray pull request #543
Opened 2023-03-26 19:47 UTC by Amereyeu

2023-03-26 19:58 UTC, Abestanis commented
Hey, thank you for these translations!
I'm a unfortunately short on time today and in the coming week, but I will review this the week after, sorry for the delay.

In the meantime, out automatic tooling has picked up some problems with the new translations (you can see it [here](https://github.com/gyunaev/birdtray/actions/runs/4526314210/jobs/7971428458?pr=543)), please have a look at them (ignore the one warning in the German translation).

2023-03-28 11:52 UTC, Abestanis requested changes
Turns out I had some time to review this, I have left some suggestions and some requests for you. Once these are resolved, I will be happy to merge this.

2023-03-28 11:52 UTC, Abestanis commented on src/translations/installer_zh_cn.ts
> +        <translation>Lang_cs</translation>
```suggestion
        <translation>捷克语</translation>
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Pokud váš správce plochy není plně kompatibilní s NETWM, možná budete muset zaškrtnout toto políčko, aby mohl detekovat okno Thunder
```suggestion
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Pokud váš správce plochy není plně kompatibilní s NETWM, možná budete muset zaškrtnout toto políčko, aby mohl detekovat okno Thunderbirdu a mohl jej minimalizovat a skrýt.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent :0px; font-size:8pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```suggestion
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style= &quot; font-size:8pt;&quot;&gt;Autorská práva (C
```suggestion
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style= &quot; font-size:8pt;&quot;&gt;Autorská práva (C) 2018 George Yunaev, &lt;/span&gt;&lt;a href=&quot;mailto:gyunaev@ulduzsoft.com&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#2980b9;&quot;&gt;gyunaev@ulduzsoft.com&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent :0px; font-size:8pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```suggestion
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```
```suggestion
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent :0px; font-size:8pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent :0px; font-size:8pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```suggestion
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style= &quot; font-size:8pt;&quot;&gt;Chcete-li požádat
```suggestion
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style= &quot; font-size:8pt;&quot;&gt;Chcete-li požádat o pomoc, funkci nebo nahlásit chybu, použijte &lt;/span&gt;&lt;a href=&quot;https://github.com/gyunaev/birdtray&quot;&gt;&lt;span style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:8pt; text-decoration: underline; color:#2980b9;&quot;&gt;Stránka projektu Github&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;.&lt;/span&gt;&lt;/p&gt;
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent :0px; font-size:8pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```suggestion
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style= &quot; font-size:8pt;&quot;&gt;Pokud chcete ocen
```suggestion
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style= &quot; font-size:8pt;&quot;&gt;Pokud chcete ocenit moji práci na Birdtray, který se vyvíjí v mém volném čase, můžete to udělat zde: &lt;/span&gt;&lt;a href=&quot;https://paypal.me/ulduzsoft&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#2980b9;&quot;&gt;https://paypal.me/ulduzsoft&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent :0px; font-size:8pt; text-decoration: underline; colo
```suggestion
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; text-decoration: underline; color:#2980b9;&quot;&gt;&lt;br /&gt;&lt;/p&gt;
```

2023-03-28 11:52 UTC, Abestanis commented on src/translations/main_cs.ts
> +        <translation>cca. %1 Mb</translation>
Is the double `c` in `cca.` intended, or is that a typo?

2023-03-28 15:22 UTC, Amereyeu commented on src/translations/installer_cs.ts
> +        <translation>BirdtraySectionDescription</translation>
will do it today

2023-04-01 13:09 UTC, Abestanis requested changes
Nice, thank you very much for the installer translations.

I have left some suggestions regarding some technical parts of the translations as well as a question for you regarding one of the translations. You can see the suggestions on GitHub and accept them from there. If you tell me, I could also do that for you. Most of them are just removing of whitespaces in places where they can cause problems.

Other than the suggestions and the one question, this looks really good, thank you. 👍

2023-04-03 20:05 UTC, merged